baseURL = "https://ceesbos.nl"
languageCode = "en-US"
title = "My gists about Observability"
theme = "gists"
pygmentsCodeFences = true
enableRobotsTXT = true
enableEmoji = true

[pagination]
    disableAliases = false
    pagerSize = 10
    path = 'page'

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[params]
    author = "Cees Bos"
    resume = "My gists about Observability"
    description = "Observability enthusiast and Grafana Champion, always looking for ways to improve software with better observability and what new insights can be gained. Delivering reliable software is always my priority. Combining existing tools often results in new ways to get an even better view. I work for OpenValue as a software & observability engineer and SRE."
    github = "cbos"
    linkedin = "https://www.linkedin.com/in/ceesbos/"
    mastodon = "https://foojay.social/@cbos"
    sessionize = "https://sessionize.com/cbos"
    bluesky = "https://bsky.app/profile/ceesbos.nl"
    keywords = "blog, technical"
    rss = true
    favicon = "/images/opentelemetry-icon-color.png"
    avatar = "/images/profile.jpeg"

[params.faro_analytics]
    endpoint = "https://faro-collector-prod-eu-west-2.grafana.net/collect/68128232fd9ac7f8c29037c86b50c1d7"
    name = "ceesbos-blog"
    version = "1.0.0"

[params.goatcounter]
    prod_url = "https://visit.ceesbos.nl"
    dev_url = "https://goatcounter.casa.ceesbos.nl"

[params.goto]
    prod_url = "https://goto.ceesbos.nl"
    dev_url = "http://localhost:8080"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[module]
[[module.imports]]
    path = 'faro-analytics'
